module.exports = {
  overrides: [
    {
      files: ['*.graphql', '*.gql'],
      parser: '@graphql-eslint/eslint-plugin',
      plugins: ['@graphql-eslint'],
      rules: {
        // The following deactivated rules generate spurious errors
        '@graphql-eslint/unique-fragment-name': 0,
        '@graphql-eslint/unique-operation-name': 0,
        '@graphql-eslint/unique-field-definition-names': 0,
        '@graphql-eslint/executable-definitions': 0,
        '@graphql-eslint/unique-type-names': 2,
        '@graphql-eslint/unique-enum-value-names': 0,

        '@graphql-eslint/require-id-when-available': 2,
        '@graphql-eslint/no-deprecated': 1,
        '@graphql-eslint/no-anonymous-operations': 2,
        '@graphql-eslint/no-operation-name-suffix': 2,
        '@graphql-eslint/avoid-duplicate-fields': 2,
        '@graphql-eslint/naming-convention': [
          'error',
          {
            ObjectTypeDefinition: 'PascalCase',
            FieldDefinition: 'camelCase',
            InputObjectTypeDefinition: 'PascalCase',
            InputValueDefinition: 'camelCase',
            EnumTypeDefinition: 'PascalCase',
            EnumValueDefinition: 'UPPER_CASE',
            InterfaceTypeDefinition: 'PascalCase',
            UnionTypeDefinition: 'PascalCase',
            ScalarTypeDefinition: 'PascalCase',
            OperationDefinition: 'PascalCase',
            QueryDefinition: 'camelCase',
            FragmentDefinition: 'camelCase',
            leadingUnderscore: 'allow',
            trailingUnderscore: 'forbid',
          },
        ],
        // This rule is deactivated because it is not compatible with
        // naming input types PascalCase but mutations camelCase
        // https://github.com/dotansimha/graphql-eslint/blob/a2b71f6be17ff57614f57b3648ae2256cc834ea9/docs/rules/input-name.md
        '@graphql-eslint/input-name': 0,
        '@graphql-eslint/fields-on-correct-type': 2,
        '@graphql-eslint/fragments-on-composite-type': 2,
        '@graphql-eslint/overlapping-fields-can-be-merged': 2,
        '@graphql-eslint/possible-fragment-spread': 2,
        '@graphql-eslint/provided-required-arguments': 2,
        '@graphql-eslint/scalar-leafs': 2,
        '@graphql-eslint/known-argument-names': 2,
        '@graphql-eslint/known-directives': 2,
        '@graphql-eslint/known-fragment-names': 2,
        '@graphql-eslint/known-type-names': 2,
        '@graphql-eslint/lone-anonymous-operation': 2,
        '@graphql-eslint/lone-schema-definition': 2,
        '@graphql-eslint/no-fragment-cycles': 2,
        '@graphql-eslint/no-undefined-variables': 2,
        '@graphql-eslint/no-unused-fragments': 2,
        '@graphql-eslint/no-unused-variables': 2,
        '@graphql-eslint/possible-type-extension': 2,
        '@graphql-eslint/unique-argument-names': 2,
        '@graphql-eslint/unique-directive-names': 2,
        '@graphql-eslint/unique-directive-names-per-location': 2,
        '@graphql-eslint/unique-input-field-names': 2,
        '@graphql-eslint/unique-operation-types': 2,
        '@graphql-eslint/unique-variable-names': 2,
        '@graphql-eslint/value-literals-of-correct-type': 2,
        '@graphql-eslint/variables-are-input-types': 2,
        '@graphql-eslint/variables-in-allowed-position': 2,
        strict: 0,
      },
    },
  ],
};
